### ISSUE TITLE
problems while sharing

### ISSUE THREAD

**Issue by afea0** [egonl/PortionOfScreen#1]
Good day, we are planning to use PortionOfScreen in our company, but we are facing various problems.
We are using a HP Z40c with a resolution of 5120x2160 pixels. To organize the screen we use Microsoft Power Toys and FancyZones. 
PortionOfScreen is fitted in a smaller zone and selected as a window to be shared. We have the problem that the shared image is only displayed in a reduced size on the opposite side. Furthermore, the program has a strange display of the background when opened. Please find pictures attached.
Contrary to other programs it is possible with Portion of Screen to hand over the control. For this reason we would like to stick to this program and kindly ask for an update. 
Kind regards

[2022-09-27_151342.pdf](https://github.com/egonl/PortionOfScreen/files/9656173/2022-09-27_151342.pdf)

**Comment by Se7enSquared** [comment]
I use this same software with fancy zones and I do not have this issue. I just snap both the window I'm sharing and the portion of screen window to the same zone and it works

**Comment by DonChunior** [comment]
I can reproduce @afea0's problem as well.
My suspicion is that it has something to do with scaling.
I tested with two HP Z40c monitors.
The sender (which has PortionOfScreen installed) has scaling set to 150%.
The receiver has 175% set and does not see the whole area shared with PortionOfScreen, but a slightly smaller one.
As if you zoomed in a little bit.

**Comment by afea0** [comment]
I'll give it a try and come back to you till the next week. Thank you.

**Comment by Larsrdev** [comment]
Hey @egonl,
I have also issues with scaling.

My setup: 
Main Screen (Laptop): 3840x2160px and 250% scaling
External Monitor: 5120x1440px and 100% scaling.

With 1.0, the PortionOfScreen content matches with the external monitor, but is zoomed in on the main screen.
With 1.1, the PortionOfScreen content matches with the main screen, but is zoomed out on the external monitor.

**Comment by afea0** [comment]
I can confirm 

> I think some or all of the issues mentioned here are indeed related to a display scale greater then 100%. Version 1.1 has a fix for this. Could you give that a try?

**Comment by afea0** [comment]
> I'll give it a try and come back to you till the next week. Thank you.

I can confirm that the program now works as desired and the scaling fits. Thank you very much!

**Comment by afea0** [comment]
> I think some or all of the issues mentioned here are indeed related to a display scale greater then 100%. Version 1.1 has a fix for this. Could you give that a try?

I can confirm that the program now works as desired and the scaling fits. Thank you very much!
