### ISSUE TITLE
PortionOfScreen 1.1 missing minimize button

### ISSUE THREAD

**Issue by ctsyeh** [egonl/PortionOfScreen#12]
Firstly, I want to say thank you for this useful tool.  

I would like to report that in version 1.0, there is a minimize button.  I upgraded to 1.1 because of resolution scaling issue and noticed that minimize button is no longer there.

Thanks.

**Comment by janxb** [comment]
Did you read the changelog for this version? It literally says:

> Removed the minimize button, so the Portion of Screen window will always be open, even when you minimize all windows. This also prevents accidentally ending the presentation by minimizing the window.

**Comment by ctsyeh** [comment]
Thanks, rookie of me to not read the fully changelog.  I was using the minimize to hide PortionOfScreen, but I guess I can use Right-Click now.

**Comment by ctsyeh** [comment]
Guess this can be closed.
