### ISSUE TITLE
Version 1.1 led teams crash when I stop sharing

### ISSUE THREAD

**Issue by reserschnell** [egonl/PortionOfScreen#7]
Hi,

I've downloaded 1.1 and since then Teams is crashing when I stop sharing. Now I've downloaded 1.0 and the problem is solved for me.
Can someone approve?

Regards

Andreas

**Comment by reserschnell** [comment]
After creating the issue, I saw that version 1.1a was released and I downloaded it. 
With this version the issue did not occur anymore. I will keep using it and provide an update if it crashes again.

**Comment by egonl** [comment]
Thanks for the report, I'll keep an eye on it as well.
